/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Screens;

import com.Controller.CustomerMasterJpaController;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author Geeth
 */
public class CustomerRegister extends javax.swing.JFrame {

    /**
     * Creates new form CustomerRegistration
     */
    EntityManagerFactory emf;
    CustomerMasterJpaController cusjpa;
    public CustomerRegister() {
        emf = Persistence.createEntityManagerFactory("InventoryControlPU");
        cusjpa = new CustomerMasterJpaController(emf);
        //int no = cusjpa.getCustomerMasterCount()+1;        
        //txtCustomerID.setText(String.valueOf(no));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        cmbTitle = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnSave = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtNic = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Registration");

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Customer Register");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 40, 350, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.Images/face.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 20, 80, 80);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.Images/ffff.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 80, 360, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Title");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 160, 90, 30);
        jPanel1.add(txtFname);
        txtFname.setBounds(130, 200, 270, 30);

        cmbTitle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr", "Mrs", "Miss" }));
        cmbTitle.setToolTipText("");
        jPanel1.add(cmbTitle);
        cmbTitle.setBounds(130, 160, 270, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("First Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 200, 90, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Middle Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 250, 90, 30);
        jPanel1.add(txtMName);
        txtMName.setBounds(130, 250, 270, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Last Name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 300, 100, 30);
        jPanel1.add(txtLname);
        txtLname.setBounds(130, 300, 270, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("No");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 350, 90, 30);
        jPanel1.add(txtNo);
        txtNo.setBounds(130, 350, 270, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Street");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 400, 90, 30);
        jPanel1.add(txtStreet);
        txtStreet.setBounds(130, 400, 270, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("City");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 450, 110, 30);
        jPanel1.add(txtCity);
        txtCity.setBounds(130, 450, 270, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mobile");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 500, 90, 30);
        jPanel1.add(txtMobile);
        txtMobile.setBounds(130, 500, 270, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Customer Id");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 120, 80, 30);

        txtCustomerID.setEditable(false);
        jPanel1.add(txtCustomerID);
        txtCustomerID.setBounds(130, 120, 270, 30);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.Images/ds.png"))); // NOI18N
        jPanel1.add(jLabel18);
        jLabel18.setBounds(430, 10, 140, 60);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.Images/save_button.png"))); // NOI18N
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        jPanel1.add(btnSave);
        btnSave.setBounds(130, 660, 120, 40);

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.Images/clear_button.png"))); // NOI18N
        jPanel1.add(btnClear);
        btnClear.setBounds(260, 660, 120, 40);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.Images/exit_button.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(390, 660, 120, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("NIC");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(40, 544, 90, 40);
        jPanel1.add(txtNic);
        txtNic.setBounds(130, 550, 270, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Fax");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(40, 590, 100, 40);
        jPanel1.add(txtFax);
        txtFax.setBounds(130, 600, 270, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.Images/register.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 750);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
        if("".equals(txtFname.getText())){
            JOptionPane.showMessageDialog(this, "First Name Field Requird");
            return;
        }else if("".equals(txtLname.getText())){
            JOptionPane.showMessageDialog(this, "Last Name Field Requird");
            return;
        }else if("".equals(txtCity.getText()) || "".equals(txtNo.getText()) || "".equals(txtStreet.getText())){
            JOptionPane.showMessageDialog(this, "Address Field Requird");
            return;
        }
    }//GEN-LAST:event_btnSaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnSave;
    private javax.swing.JComboBox<String> cmbTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtMName;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtStreet;
    // End of variables declaration//GEN-END:variables
}
